### ISSUE TITLE
Messed up PDF files

### ISSUE THREAD

**Issue by bandali** [otherjoel/thenotepad#1]
Hi Joel,

I'm not sure if you've noticed or not, but the content of the PDF files on https://thenotepad.org are messed up, they don't correspond to the post they're linked in (or to their name).

**Comment by otherjoel** [comment]
Thanks! Looks like a couple of bugs conspired here. Should be fixed now.

**Comment by bandali** [comment]
No problems, and yeah looks like it's fixed! Closing this.
