### ISSUE TITLE
Call to mvim

### ISSUE THREAD

**Issue by skypher** [otherjoel/thenotepad#10]
I'm not sure about Mac, but usually on a UNIX system, instead of hard-coding the editor you would call out to whatever $EDITOR contains. Failing that, a somewhat sane default can be employed, for example emitting a message that tells the user to set $EDITOR.

What's your take?

**Comment by otherjoel** [comment]
Good point. I don’t personally use `$EDITOR` at this point, so I’m not interested in coding this myself. But I’m open to a pull request that makes use of it, as long as it checks to make sure the value contains something before using it, and has a fallback in case it is empty.

**Comment by otherjoel** [comment]
Since `newpost.rkt` is just a helper/convenience script and not really necessary for any part of publishing, I’m going to close this for now.
